# Default values for matatika-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: local/matatika-app
  # Specify a specific image version to override default ({{ .Release.appVersion }})
  #tag: latest
  private: false
  #password: [your docker registry password]
  ## Specify an imagePullPolicy (Required)
  ## Use 'Never' if this is local development, 'Always' if the image is deployed using latest
  ## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
  ##
  pullPolicy: Never

appService:
  name: app
  type: ClusterIP
  httpPort: 80
  httpsPort: 443
  internalHttpPort: 80
  environments:
    - name: APP_SERVER_URI
      value: "http://somehost.somewhere.com"
    - name: APP_IDENTITY_DOMAIN
      value: "matatika.eu.auth0.com"
    - name: APP_IDENTITY_CLIENT_ID
      value: "configureavalue"

ingress:
  enabled: true
  paths:
    - /
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - app-staging.matatika.com
  annotations:
    # kubernetes.io/ingress.class: addon-http-application-routing  
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - app-staging.matatika.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
