# Default values for matatika-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
# We are using --set specify a specific image version to override default ({{ .Release.appVersion }})
#tag: latest
#
# To use a private repository you'll need all of the following
#
  private: true
  name: matatika.azurecr.io/matatika-app
  repository: matatika.azurecr.io
  username: matatika
#  password: [we are using --set]
  pullPolicy: Always

appService:
  name: nginx
  type: ClusterIP
  nodePool: nodepool2
  httpPort: 80
  httpsPort: 443
  internalHttpPort: 80
  environments:
    - name: REACT_APP_ENV
      value: "production"
    - name: APP_IDENTITY_CLIENT_ID
      value: <auth0_app_identity_client_id>
    - name: APP_SERVER_URI
      value: https://catalog-example.matatika.com/api
    - name: APP_URL
      value: https://example.matatika.com

ingress:
  enabled: true
  paths:
    - /
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - app.44b3fe4de4104e2d8e43.uksouth.aksapp.io
    - example.matatika.com
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - app.44b3fe4de4104e2d8e43.uksouth.aksapp.io
      - example.matatika.com
      
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
