apiVersion: v1
kind: Service
metadata:
  name: {{ include "matatika-catalog.fullname" . }}-{{ .Values.appService.name }}
  {{- with .Values.appService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.appService.type }}
  ports:
  - name: http
    port: {{ .Values.appService.httpPort }}
    targetPort: {{ .Values.appService.targetPort }} # app-http
    protocol: TCP
  selector:
    app: {{ template "matatika-catalog.fullname" . }}-app
