apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-appsecrets
data:
  auth0_client_secret: {{ .Values.appService.auth0ClientSecret | b64enc }}
  github_api_private_key: {{ .Values.appService.githubApiPrivateKey | b64enc }}
  github_api_workspaces_private_key: {{ .Values.appService.githubApiWorkspacesPrivateKey | b64enc }}
  persistence_warehouse_pass: {{ .Values.appService.persistenceWarehousePass | b64enc }}
  persistence_catalog_pass: {{ .Values.appService.persistenceCatalogPass | b64enc }}
  es_elastic_pass: {{ .Values.appService.elasticSearchPassword | b64enc }}
  encryptor_pass: {{ .Values.appService.encryptorPassword | b64enc }}
  azurecr_registry_secret: {{ .Values.image.password | b64enc }}