apiVersion: v1
kind: Service
metadata:
  name: {{ include "matatika-app.fullname" . }}-{{ .Values.appService.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.appService.type }}
  ports:
  - name: http
    port: {{ .Values.appService.httpPort }}
    targetPort: app-http
    protocol: TCP
  selector:
    app: {{ template "matatika-app.fullname" . }}-app
