apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStoreName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "meltano-secrets.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ required "projectId is required" .Values.projectId | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ required "cluster.location is required" .Values.cluster.location | quote }}
          clusterName: {{ required "cluster.name is required" .Values.cluster.name | quote }}
          serviceAccountRef:
            name: {{ required "serviceAccountName is required" .Values.serviceAccountName | quote }}
