{{- if .Values.persistence.storageAccountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-azurefile
data:
  azurestorageaccountname: {{ .Values.persistence.storageAccount | b64enc }}
  azurestorageaccountkey: {{ .Values.persistence.storageAccountKey | b64enc }}
{{- end }}