{{- if and (eq .Values.persistence.storageClass "custom") (not .Values.persistence.existingClaim) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "matatika-www.fullname" . }}-{{ .Values.persistence.storageClass }}
provisioner: file.csi.azure.com
mountOptions:
  - dir_mode=0777
  - file_mode=0644
  - uid=1001
  - gid=33
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
  storageAccount: {{ .Values.persistence.storageAccount }}
  {{- if .Values.persistence.shareName }}
  shareName: {{ .Values.persistence.shareName }}
  {{- end }}
  {{- if .Values.persistence.storageAccountKey }}
  secretName: {{ .Release.Name }}-azurefile
  {{- end }}
  resourceGroup: {{ .Values.persistence.resourceGroup }}
reclaimPolicy: Retain
{{- end }}
